export default [
  {
    lesson: "hello-world",
    title: "Hello, world!",
    // source: require("./exercises/01.js").default,
    source: require("./solutions/01.final").default,
    hintSource: require("./exercises/01.md"),
  },
  {
    lesson: "capturing-taps",
    title: "Capturing Taps",
    // source: require("./exercises/02.js").default,
    // source: require("./solutions/02.final").default,
    source: require("./solutions/02.extra-1").default,
    hintSource: require("./exercises/02.md"),
  },
  {
    lesson: "custom-component",
    title: "Custom Component",
    // source: require("./solutions/03.final").default,
    source: require("./solutions/03.extra-1").default,
    // hintSource: require("./exercises/03.md"),
  },
  {
    lesson: "state-props",
    title: "State & Props",
    // source: require("./solutions/04.final").default,
    source: require("./solutions/04.extra-1").default,
    // hintSource: require("./exercises/04.md"),
  },
  {
    lesson: "styling",
    title: "Styling",
    // source: require("./solutions/05.final").default,
    source: require("./solutions/05.extra-1").default,
    // hintSource: require("./exercises/05.md"),
  },
  {
    lesson: "scrollable-content",
    title: "Scrollable Content",
    source: require("./solutions/06.final").default,
    // hintSource: require("./exercises/06.md"),
  },
  {
    lesson: "building-a-form",
    title: "Building a Form",
    source: require("./solutions/07.final").default,
  },
  {
    lesson: "long-lists",
    title: "Long Lists",
    // source: require("./solutions/08.final").default,
    source: require("./solutions/08.extra-1").default,
  },
  {
    lesson: "working-with-api",
    title: "Working with an API",
    // source: require("./solutions/09.final").default,
    // source: require("./solutions/09.extra-1").default,
    source: require("./solutions/09.extra-2").default,
  },
  {
    lesson: "multiple-files",
    title: "Mulitple Files",
    source: require("./solutions/10.final").default,
  },
  {
    lesson: "class-components",
    title: "Class Components",
    source: require("./solutions/11.final").default,
  },
  {
    lesson: "component-lifecycle",
    title: "Component Lifecycle",
    // source: require("./solutions/12.final").default,
    source: require("./solutions/12.extra-1").default,
  },
];
